# Generated by Django 5.2.3 on 2025-07-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaatuacao',
            options={'verbose_name': 'Áreas de Atuação', 'verbose_name_plural': 'Áreas de Atuação'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
    ]
